# config/routes.yaml

index:
    path: /
    controller: App\Controller\SorteoController::index

app_numero_sorteo:
    path: /sorteo/numero/{maximo}
    controller: App\Controller\SorteoController::numero
    defaults:
        maximo: 100

app_suma:
    path: /suma/{numero1}/{numero2}
    controller: App\Controller\SorteoController::suma
    defaults:
        numero1: 2
        numero2: 2

app_euromillones:
    path: /sorteo/euromillones
    controller: App\Controller\SorteoController::euromillones